openapi: 3.0.1
info:
  title: microservicio-usuarioCuenta
  version: v0
servers:
  - url: http://localhost:8080
    description: usuarioCuenta
paths:
  /api/usuarios/id/{id}:
    get:
      tags:
        - usuario-controller
      operationId: getUsuarioById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/UsuarioDTO'
    put:
      tags:
        - usuario-controller
      operationId: updateUsuario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Usuario'
    delete:
      tags:
        - usuario-controller
      operationId: deleteUsuario
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/cuentas/id/{id}:
    get:
      tags:
        - cuenta-controller
      operationId: getCuentaById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CuentaDTO'
    put:
      tags:
        - cuenta-controller
      operationId: updateCuenta
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cuenta'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Cuenta'
  /api/cuentas/id/{idCuenta}/desanularCuenta:
    put:
      tags:
        - cuenta-controller
      operationId: desanularCuenta
      parameters:
        - name: idCuenta
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/cuentas/id/{idCuenta}/anularCuenta:
    put:
      tags:
        - cuenta-controller
      operationId: anularCuenta
      parameters:
        - name: idCuenta
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/usuarios:
    post:
      tags:
        - usuario-controller
      operationId: addUsuario
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Usuario'
        required: true
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Usuario'
  /api/cuentas:
    get:
      tags:
        - cuenta-controller
      operationId: getCuentas
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CuentaDTO'
    post:
      tags:
        - cuenta-controller
      operationId: addCuenta
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Cuenta'
        required: true
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Cuenta'
  /api/cuentas/id/{idCuenta}:
    delete:
      tags:
        - cuenta-controller
      operationId: deleteCuenta
      parameters:
        - name: idCuenta
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Cuenta:
      type: object
      properties:
        id:
          type: integer
          format: int32
        saldo:
          type: number
          format: double
        fechaAlta:
          type: string
          format: date-time
        idMercadoPago:
          type: integer
          format: int32
        usuarios:
          type: array
          items:
            $ref: '#/components/schemas/Usuario'
        anulada:
          type: boolean
    Usuario:
      type: object
      properties:
        id:
          type: integer
          format: int32
        nombre:
          type: string
        nombreUsuario:
          type: string
        apellido:
          type: string
        email:
          type: string
        telefono:
          type: string
        cuentas:
          type: array
          items:
            $ref: '#/components/schemas/Cuenta'
    UsuarioDTO:
      type: object
    CuentaDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        saldo:
          type: number
          format: double
        fechaAlta:
          type: string
          format: date-time
        idMercadoPago:
          type: integer
          format: int32
        anulada:
          type: boolean
