openapi: 3.0.1
info:
  title: microservicio-mantenimiento
  version: v0
servers:
  - url: http://localhost:8080
    description: mantenimiento
paths:
  /api/tarifas/setPrecioTarifaExtra/id/{idTarifa}:
    put:
      tags:
        - tarifa-controller
      operationId: setPrecioTarifaExtra
      parameters:
        - name: idTarifa
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      requestBody:
        content:
          application/json:
            schema:
              type: integer
              format: int32
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/tarifas/setPrecioTarifa/id/{idTarifa}:
    put:
      tags:
        - tarifa-controller
      operationId: setPrecioTarifa
      parameters:
        - name: idTarifa
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      requestBody:
        content:
          application/json:
            schema:
              type: integer
              format: int32
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/tarifas/id/{id}:
    get:
      tags:
        - tarifa-controller
      operationId: getTarifaById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TarifaDTO'
    put:
      tags:
        - tarifa-controller
      operationId: updateTarifa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tarifa'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Tarifa'
    delete:
      tags:
        - tarifa-controller
      operationId: deleteTarifa
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/mantenimientos/id/{id}:
    get:
      tags:
        - mantenimiento-controller
      operationId: getMantenimientoById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MantenimientoDTO'
    put:
      tags:
        - mantenimiento-controller
      operationId: updateMantenimiento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mantenimiento'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Mantenimiento'
  /api/mantenimientos/id/{id}/finalizar:
    put:
      tags:
        - mantenimiento-controller
      operationId: finalizarMantenimiento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      requestBody:
        content:
          application/json:
            schema:
              type: string
              format: date-time
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/tarifas:
    get:
      tags:
        - tarifa-controller
      operationId: getTarifas
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TarifaDTO'
    post:
      tags:
        - tarifa-controller
      operationId: addTarifa
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tarifa'
        required: true
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Tarifa'
  /api/mantenimientos:
    get:
      tags:
        - mantenimiento-controller
      operationId: getMantenimientos
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MantenimientoDTO'
    post:
      tags:
        - mantenimiento-controller
      operationId: addMantenimiento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Mantenimiento'
        required: true
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/tarifas/actual:
    get:
      tags:
        - tarifa-controller
      operationId: getTarifaActual
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/TarifaDTO'
  /api/reportes/monopatines/tiempoSinPausa:
    get:
      tags:
        - reporte-controller
      operationId: getReporteMonopatinesPorTiempoSinPausa
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReporteDTO'
  /api/reportes/monopatines/tiempoPausa:
    get:
      tags:
        - reporte-controller
      operationId: getReporteMonopatinesPorTiempoPausa
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReporteDTO'
  /api/reportes/monopatines/kilometros/tiempos/{quieroTiempos}:
    get:
      tags:
        - reporte-controller
      operationId: getReporteMonopatinesPorKilometro
      parameters:
        - name: quieroTiempos
          in: path
          required: true
          schema:
            type: boolean
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ReporteDTO'
  /api/mantenimientos/id/{idMantenimiento}:
    delete:
      tags:
        - mantenimiento-controller
      operationId: deleteMantenimiento
      parameters:
        - name: idMantenimiento
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            description: Bearer token
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    Tarifa:
      type: object
      properties:
        id:
          type: integer
          format: int32
        precioTarifa:
          type: integer
          format: int32
        precioTarifaExtra:
          type: integer
          format: int32
        fecha:
          type: string
          format: date
    Mantenimiento:
      type: object
      properties:
        id:
          type: integer
          format: int32
        idMonopatin:
          type: integer
          format: int32
        fechaInicio:
          type: string
          format: date-time
        fechaFin:
          type: string
          format: date-time
    TarifaDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        precioTarifa:
          type: number
          format: double
        precioTarifaExtra:
          type: number
          format: double
        fecha:
          type: string
          format: date
    ReporteDTO:
      type: object
      properties:
        idMonopatin:
          type: integer
          format: int32
        kmRecorridos:
          type: number
          format: double
        tiempoPausa:
          type: integer
          format: int64
        tiempoSinPausa:
          type: integer
          format: int64
    MantenimientoDTO:
      type: object
      properties:
        id:
          type: integer
          format: int32
        idMonopatin:
          type: integer
          format: int32
        fechaInicio:
          type: string
          format: date-time
        fechaFin:
          type: string
          format: date-time
